---

version: '3.9'
services:
        nginx:
                container_name: test-nginx
                image: 294360715377.dkr.ecr.us-east-1.amazonaws.com/webserver:nginx
                ports:
                  - "80:80"
                volumes:
                  - ./static/:/usr/share/nginx/html
                networks:
                  default:
                depends_on:
                  - wordpress
        wordpress:
                container_name: test-wordpress
                image: 294360715377.dkr.ecr.us-east-1.amazonaws.com/webserver:wordpress
                networks:
                  default:

networks:
  default:
    driver: bridge
